package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GoodsReceipt generated by hbm2java
 */
@Entity
@Table(name = "goods_receipt", catalog = "sywm")
public class GoodsReceipt implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer goodsReceiptId;
	private ArrivalPlan arrivalPlan;
	private GoodsOwner goodsOwner;
	private String goodsReceiptCode;
	private String deliverContact;
	private String deliverContactTel;
	private Date receiptTime;
	private String receiptDiffExplain;
	private int receiptStatus;

	public GoodsReceipt() {
	}

	public GoodsReceipt(ArrivalPlan arrivalPlan, GoodsOwner goodsOwner, String goodsReceiptCode, String deliverContact,
			String deliverContactTel, Date receiptTime, String receiptDiffExplain, int receiptStatus) {
		this.arrivalPlan = arrivalPlan;
		this.goodsOwner = goodsOwner;
		this.goodsReceiptCode = goodsReceiptCode;
		this.deliverContact = deliverContact;
		this.deliverContactTel = deliverContactTel;
		this.receiptTime = receiptTime;
		this.receiptDiffExplain = receiptDiffExplain;
		this.receiptStatus = receiptStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "goods_receipt_id", unique = true, nullable = false)
	public Integer getGoodsReceiptId() {
		return this.goodsReceiptId;
	}

	public void setGoodsReceiptId(Integer goodsReceiptId) {
		this.goodsReceiptId = goodsReceiptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "arrival_plan_id", nullable = false)
	public ArrivalPlan getArrivalPlan() {
		return this.arrivalPlan;
	}

	public void setArrivalPlan(ArrivalPlan arrivalPlan) {
		this.arrivalPlan = arrivalPlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@Column(name = "goods_receipt_code", nullable = false, length = 20)
	public String getGoodsReceiptCode() {
		return this.goodsReceiptCode;
	}

	public void setGoodsReceiptCode(String goodsReceiptCode) {
		this.goodsReceiptCode = goodsReceiptCode;
	}

	@Column(name = "deliver_contact", nullable = false, length = 20)
	public String getDeliverContact() {
		return this.deliverContact;
	}

	public void setDeliverContact(String deliverContact) {
		this.deliverContact = deliverContact;
	}

	@Column(name = "deliver_contact_tel", nullable = false, length = 20)
	public String getDeliverContactTel() {
		return this.deliverContactTel;
	}

	public void setDeliverContactTel(String deliverContactTel) {
		this.deliverContactTel = deliverContactTel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "receipt_time", nullable = false, length = 19)
	public Date getReceiptTime() {
		return this.receiptTime;
	}

	public void setReceiptTime(Date receiptTime) {
		this.receiptTime = receiptTime;
	}

	@Column(name = "receipt_diff_explain", nullable = false, length = 100)
	public String getReceiptDiffExplain() {
		return this.receiptDiffExplain;
	}

	public void setReceiptDiffExplain(String receiptDiffExplain) {
		this.receiptDiffExplain = receiptDiffExplain;
	}

	@Column(name = "receipt_status", nullable = false)
	public int getReceiptStatus() {
		return this.receiptStatus;
	}

	public void setReceiptStatus(int receiptStatus) {
		this.receiptStatus = receiptStatus;
	}

}
