package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Driver generated by hbm2java
 */
@Entity
@Table(name = "driver", catalog = "sywm")
public class Driver implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer driverId;
	private String driverName;
	private String driverMobile;
	private String loginName;
	private String loginPwd;
	private String pwdSalt;
	private boolean isDelete;
	private Set<Sorting> sortings = new HashSet<Sorting>(0);
	private Set<ShipInfo> shipInfos = new HashSet<ShipInfo>(0);
	private Set<ReturnInfo> returnInfos = new HashSet<ReturnInfo>(0);

	public Driver() {
	}

	public Driver(String driverName, String loginName, String loginPwd, String pwdSalt, boolean isDelete) {
		this.driverName = driverName;
		this.loginName = loginName;
		this.loginPwd = loginPwd;
		this.pwdSalt = pwdSalt;
		this.isDelete = isDelete;
	}

	public Driver(String driverName, String driverMobile, String loginName, String loginPwd, String pwdSalt,
			boolean isDelete, Set<Sorting> sortings, Set<ShipInfo> shipInfos, Set<ReturnInfo> returnInfos) {
		this.driverName = driverName;
		this.driverMobile = driverMobile;
		this.loginName = loginName;
		this.loginPwd = loginPwd;
		this.pwdSalt = pwdSalt;
		this.isDelete = isDelete;
		this.sortings = sortings;
		this.shipInfos = shipInfos;
		this.returnInfos = returnInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "driver_id", unique = true, nullable = false)
	public Integer getDriverId() {
		return this.driverId;
	}

	public void setDriverId(Integer driverId) {
		this.driverId = driverId;
	}

	@Column(name = "driver_name", nullable = false, length = 20)
	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	@Column(name = "driver_mobile", length = 20)
	public String getDriverMobile() {
		return this.driverMobile;
	}

	public void setDriverMobile(String driverMobile) {
		this.driverMobile = driverMobile;
	}

	@Column(name = "login_name", nullable = false, length = 20)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "login_pwd", nullable = false, length = 88)
	public String getLoginPwd() {
		return this.loginPwd;
	}

	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	@Column(name = "pwd_salt", nullable = false, length = 44)
	public String getPwdSalt() {
		return this.pwdSalt;
	}

	public void setPwdSalt(String pwdSalt) {
		this.pwdSalt = pwdSalt;
	}

	@Column(name = "is_delete", nullable = false)
	public boolean isIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "driver")
	public Set<Sorting> getSortings() {
		return this.sortings;
	}

	public void setSortings(Set<Sorting> sortings) {
		this.sortings = sortings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "driver")
	public Set<ShipInfo> getShipInfos() {
		return this.shipInfos;
	}

	public void setShipInfos(Set<ShipInfo> shipInfos) {
		this.shipInfos = shipInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "driver")
	public Set<ReturnInfo> getReturnInfos() {
		return this.returnInfos;
	}

	public void setReturnInfos(Set<ReturnInfo> returnInfos) {
		this.returnInfos = returnInfos;
	}

}
