package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Recipient generated by hbm2java
 */
@Entity
@Table(name = "recipient", catalog = "sywm")
public class Recipient implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer recipientId;
	private GoodsOwner goodsOwner;
	private String recipientCode;
	private String recipientName;
	private String recipientAddress;
	private String recipientContact;
	private String recipientContactPhone;
	private Set<DeliverOrder> deliverOrders = new HashSet<DeliverOrder>(0);

	public Recipient() {
	}

	public Recipient(GoodsOwner goodsOwner, String recipientCode, String recipientName, String recipientAddress,
			String recipientContact, String recipientContactPhone) {
		this.goodsOwner = goodsOwner;
		this.recipientCode = recipientCode;
		this.recipientName = recipientName;
		this.recipientAddress = recipientAddress;
		this.recipientContact = recipientContact;
		this.recipientContactPhone = recipientContactPhone;
	}

	public Recipient(GoodsOwner goodsOwner, String recipientCode, String recipientName, String recipientAddress,
			String recipientContact, String recipientContactPhone, Set<DeliverOrder> deliverOrders) {
		this.goodsOwner = goodsOwner;
		this.recipientCode = recipientCode;
		this.recipientName = recipientName;
		this.recipientAddress = recipientAddress;
		this.recipientContact = recipientContact;
		this.recipientContactPhone = recipientContactPhone;
		this.deliverOrders = deliverOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recipient_id", unique = true, nullable = false)
	public Integer getRecipientId() {
		return this.recipientId;
	}

	public void setRecipientId(Integer recipientId) {
		this.recipientId = recipientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@Column(name = "recipient_code", nullable = false, length = 20)
	public String getRecipientCode() {
		return this.recipientCode;
	}

	public void setRecipientCode(String recipientCode) {
		this.recipientCode = recipientCode;
	}

	@Column(name = "recipient_name", nullable = false, length = 50)
	public String getRecipientName() {
		return this.recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	@Column(name = "recipient_address", nullable = false, length = 100)
	public String getRecipientAddress() {
		return this.recipientAddress;
	}

	public void setRecipientAddress(String recipientAddress) {
		this.recipientAddress = recipientAddress;
	}

	@Column(name = "recipient_contact", nullable = false, length = 20)
	public String getRecipientContact() {
		return this.recipientContact;
	}

	public void setRecipientContact(String recipientContact) {
		this.recipientContact = recipientContact;
	}

	@Column(name = "recipient_contact_phone", nullable = false, length = 20)
	public String getRecipientContactPhone() {
		return this.recipientContactPhone;
	}

	public void setRecipientContactPhone(String recipientContactPhone) {
		this.recipientContactPhone = recipientContactPhone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recipient")
	public Set<DeliverOrder> getDeliverOrders() {
		return this.deliverOrders;
	}

	public void setDeliverOrders(Set<DeliverOrder> deliverOrders) {
		this.deliverOrders = deliverOrders;
	}

}
