package com.rescam.sywm.server.entity;
// Generated 2016-7-1 17:29:15 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShipDetail generated by hbm2java
 */
@Entity
@Table(name = "ship_detail", catalog = "sywm")
public class ShipDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer shipDetailId;
	private CommodityBase commodityBase;
	private CommodityPacking commodityPacking;
	private DeliverOrder deliverOrder;
	private GoodsOwner goodsOwner;
	private GoodsOwnerCommodity goodsOwnerCommodity;
	private ShipInfo shipInfo;
	private Sorting sorting;
	private Integer paymentId;
	private String shipCode;
	private String orderCode;
	private String goodsOwnerCommodityCode;
	private String commodityBarcode;
	private String commodityName;
	private String commodityStandard;
	private String commodityPackingUnit;
	private int commodityPackingQuantity;
	private int saleQuantity;
	private BigDecimal saleUnitPrice;
	private BigDecimal salePrice;
	private Boolean isReturn;
	private Date receiptTime;
	private String receiptPeople;
	private String paymentDriverName;
	private String payee;
	private Date receivablesTime;
	private BigDecimal receivablesAmount;

	public ShipDetail() {
	}

	public ShipDetail(CommodityBase commodityBase, CommodityPacking commodityPacking, DeliverOrder deliverOrder,
			GoodsOwner goodsOwner, GoodsOwnerCommodity goodsOwnerCommodity, ShipInfo shipInfo, Sorting sorting,
			String shipCode, String orderCode, String commodityBarcode, String commodityName, String commodityStandard,
			String commodityPackingUnit, int commodityPackingQuantity, int saleQuantity, BigDecimal saleUnitPrice,
			BigDecimal salePrice) {
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.deliverOrder = deliverOrder;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.shipInfo = shipInfo;
		this.sorting = sorting;
		this.shipCode = shipCode;
		this.orderCode = orderCode;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.saleQuantity = saleQuantity;
		this.saleUnitPrice = saleUnitPrice;
		this.salePrice = salePrice;
	}

	public ShipDetail(CommodityBase commodityBase, CommodityPacking commodityPacking, DeliverOrder deliverOrder,
			GoodsOwner goodsOwner, GoodsOwnerCommodity goodsOwnerCommodity, ShipInfo shipInfo, Sorting sorting,
			Integer paymentId, String shipCode, String orderCode, String goodsOwnerCommodityCode,
			String commodityBarcode, String commodityName, String commodityStandard, String commodityPackingUnit,
			int commodityPackingQuantity, int saleQuantity, BigDecimal saleUnitPrice, BigDecimal salePrice,
			Boolean isReturn, Date receiptTime, String receiptPeople, String paymentDriverName, String payee,
			Date receivablesTime, BigDecimal receivablesAmount) {
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.deliverOrder = deliverOrder;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.shipInfo = shipInfo;
		this.sorting = sorting;
		this.paymentId = paymentId;
		this.shipCode = shipCode;
		this.orderCode = orderCode;
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.saleQuantity = saleQuantity;
		this.saleUnitPrice = saleUnitPrice;
		this.salePrice = salePrice;
		this.isReturn = isReturn;
		this.receiptTime = receiptTime;
		this.receiptPeople = receiptPeople;
		this.paymentDriverName = paymentDriverName;
		this.payee = payee;
		this.receivablesTime = receivablesTime;
		this.receivablesAmount = receivablesAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ship_detail_id", unique = true, nullable = false)
	public Integer getShipDetailId() {
		return this.shipDetailId;
	}

	public void setShipDetailId(Integer shipDetailId) {
		this.shipDetailId = shipDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_base_id", nullable = false)
	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodityBase) {
		this.commodityBase = commodityBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_packing_id", nullable = false)
	public CommodityPacking getCommodityPacking() {
		return this.commodityPacking;
	}

	public void setCommodityPacking(CommodityPacking commodityPacking) {
		this.commodityPacking = commodityPacking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deliver_order_id", nullable = false)
	public DeliverOrder getDeliverOrder() {
		return this.deliverOrder;
	}

	public void setDeliverOrder(DeliverOrder deliverOrder) {
		this.deliverOrder = deliverOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_commodity_id", nullable = false)
	public GoodsOwnerCommodity getGoodsOwnerCommodity() {
		return this.goodsOwnerCommodity;
	}

	public void setGoodsOwnerCommodity(GoodsOwnerCommodity goodsOwnerCommodity) {
		this.goodsOwnerCommodity = goodsOwnerCommodity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ship_info_id", nullable = false)
	public ShipInfo getShipInfo() {
		return this.shipInfo;
	}

	public void setShipInfo(ShipInfo shipInfo) {
		this.shipInfo = shipInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sorting_id", nullable = false)
	public Sorting getSorting() {
		return this.sorting;
	}

	public void setSorting(Sorting sorting) {
		this.sorting = sorting;
	}

	@Column(name = "payment_id")
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "ship_code", nullable = false, length = 14)
	public String getShipCode() {
		return this.shipCode;
	}

	public void setShipCode(String shipCode) {
		this.shipCode = shipCode;
	}

	@Column(name = "order_code", nullable = false, length = 14)
	public String getOrderCode() {
		return this.orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	@Column(name = "goods_owner_commodity_code", length = 20)
	public String getGoodsOwnerCommodityCode() {
		return this.goodsOwnerCommodityCode;
	}

	public void setGoodsOwnerCommodityCode(String goodsOwnerCommodityCode) {
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
	}

	@Column(name = "commodity_barcode", nullable = false, length = 20)
	public String getCommodityBarcode() {
		return this.commodityBarcode;
	}

	public void setCommodityBarcode(String commodityBarcode) {
		this.commodityBarcode = commodityBarcode;
	}

	@Column(name = "commodity_name", nullable = false, length = 50)
	public String getCommodityName() {
		return this.commodityName;
	}

	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	@Column(name = "commodity_standard", nullable = false, length = 50)
	public String getCommodityStandard() {
		return this.commodityStandard;
	}

	public void setCommodityStandard(String commodityStandard) {
		this.commodityStandard = commodityStandard;
	}

	@Column(name = "commodity_packing_unit", nullable = false, length = 10)
	public String getCommodityPackingUnit() {
		return this.commodityPackingUnit;
	}

	public void setCommodityPackingUnit(String commodityPackingUnit) {
		this.commodityPackingUnit = commodityPackingUnit;
	}

	@Column(name = "commodity_packing_quantity", nullable = false)
	public int getCommodityPackingQuantity() {
		return this.commodityPackingQuantity;
	}

	public void setCommodityPackingQuantity(int commodityPackingQuantity) {
		this.commodityPackingQuantity = commodityPackingQuantity;
	}

	@Column(name = "sale_quantity", nullable = false)
	public int getSaleQuantity() {
		return this.saleQuantity;
	}

	public void setSaleQuantity(int saleQuantity) {
		this.saleQuantity = saleQuantity;
	}

	@Column(name = "sale_unit_price", nullable = false, precision = 15)
	public BigDecimal getSaleUnitPrice() {
		return this.saleUnitPrice;
	}

	public void setSaleUnitPrice(BigDecimal saleUnitPrice) {
		this.saleUnitPrice = saleUnitPrice;
	}

	@Column(name = "sale_price", nullable = false, precision = 15)
	public BigDecimal getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

	@Column(name = "is_return")
	public Boolean getIsReturn() {
		return this.isReturn;
	}

	public void setIsReturn(Boolean isReturn) {
		this.isReturn = isReturn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "receipt_time", length = 10)
	public Date getReceiptTime() {
		return this.receiptTime;
	}

	public void setReceiptTime(Date receiptTime) {
		this.receiptTime = receiptTime;
	}

	@Column(name = "receipt_people", length = 20)
	public String getReceiptPeople() {
		return this.receiptPeople;
	}

	public void setReceiptPeople(String receiptPeople) {
		this.receiptPeople = receiptPeople;
	}

	@Column(name = "payment_driver_name", length = 20)
	public String getPaymentDriverName() {
		return this.paymentDriverName;
	}

	public void setPaymentDriverName(String paymentDriverName) {
		this.paymentDriverName = paymentDriverName;
	}

	@Column(name = "payee", length = 20)
	public String getPayee() {
		return this.payee;
	}

	public void setPayee(String payee) {
		this.payee = payee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "receivables_time", length = 19)
	public Date getReceivablesTime() {
		return this.receivablesTime;
	}

	public void setReceivablesTime(Date receivablesTime) {
		this.receivablesTime = receivablesTime;
	}

	@Column(name = "receivables_amount", precision = 15)
	public BigDecimal getReceivablesAmount() {
		return this.receivablesAmount;
	}

	public void setReceivablesAmount(BigDecimal receivablesAmount) {
		this.receivablesAmount = receivablesAmount;
	}

}
