package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockBoxs generated by hbm2java
 */
@Entity
@Table(name = "stock_boxs", catalog = "sywm")
public class StockBoxs implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer stockBoxsId;
	private ArrivalPlanDetails arrivalPlanDetails;
	private CommodityBase commodityBase;
	private CommodityPacking commodityPacking;
	private DamageDetails damageDetails;
	private GoodsLocator goodsLocator;
	private GoodsOwner goodsOwner;
	private GoodsOwnerCommodity goodsOwnerCommodity;
	private LoadPallets loadPallets;
	private Pallets pallets;
	private StorageAreas storageAreas;
	private StorageRacks storageRacks;
	private UserInfo userInfoByUnpackingUserId;
	private UserInfo userInfoByPasteUserId;
	private Warehouse warehouse;
	private int goodsReceiptDetailsId;
	private Integer sortingDetailsId;
	private Integer receiptReturnDetailsId;
	private String palletsCode;
	private String goodsOwnerCommodityCode;
	private String commodityBarcode;
	private String commodityName;
	private String commodityStandard;
	private String commodityPackingUnit;
	private int commodityPackingQuantity;
	private Date madeTime;
	private Date soonExpire;
	private Date shelfLife;
	private boolean isDamage;
	private String boxCode;
	private int boxInQuantity;
	private boolean isUnpacking;
	private Date pasteTime;
	private Date unpackingTime;

	public StockBoxs() {
	}

	public StockBoxs(ArrivalPlanDetails arrivalPlanDetails, CommodityBase commodityBase,
			CommodityPacking commodityPacking, GoodsLocator goodsLocator, GoodsOwner goodsOwner,
			GoodsOwnerCommodity goodsOwnerCommodity, LoadPallets loadPallets, Pallets pallets,
			UserInfo userInfoByUnpackingUserId, UserInfo userInfoByPasteUserId, Warehouse warehouse,
			int goodsReceiptDetailsId, String palletsCode, String goodsOwnerCommodityCode, String commodityBarcode,
			String commodityName, String commodityStandard, String commodityPackingUnit, int commodityPackingQuantity,
			Date madeTime, Date soonExpire, Date shelfLife, boolean isDamage, String boxCode, int boxInQuantity,
			boolean isUnpacking, Date pasteTime, Date unpackingTime) {
		this.arrivalPlanDetails = arrivalPlanDetails;
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.goodsLocator = goodsLocator;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.loadPallets = loadPallets;
		this.pallets = pallets;
		this.userInfoByUnpackingUserId = userInfoByUnpackingUserId;
		this.userInfoByPasteUserId = userInfoByPasteUserId;
		this.warehouse = warehouse;
		this.goodsReceiptDetailsId = goodsReceiptDetailsId;
		this.palletsCode = palletsCode;
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.madeTime = madeTime;
		this.soonExpire = soonExpire;
		this.shelfLife = shelfLife;
		this.isDamage = isDamage;
		this.boxCode = boxCode;
		this.boxInQuantity = boxInQuantity;
		this.isUnpacking = isUnpacking;
		this.pasteTime = pasteTime;
		this.unpackingTime = unpackingTime;
	}

	public StockBoxs(ArrivalPlanDetails arrivalPlanDetails, CommodityBase commodityBase,
			CommodityPacking commodityPacking, DamageDetails damageDetails, GoodsLocator goodsLocator,
			GoodsOwner goodsOwner, GoodsOwnerCommodity goodsOwnerCommodity, LoadPallets loadPallets, Pallets pallets,
			StorageAreas storageAreas, StorageRacks storageRacks, UserInfo userInfoByUnpackingUserId,
			UserInfo userInfoByPasteUserId, Warehouse warehouse, int goodsReceiptDetailsId, Integer sortingDetailsId,
			Integer receiptReturnDetailsId, String palletsCode, String goodsOwnerCommodityCode, String commodityBarcode,
			String commodityName, String commodityStandard, String commodityPackingUnit, int commodityPackingQuantity,
			Date madeTime, Date soonExpire, Date shelfLife, boolean isDamage, String boxCode, int boxInQuantity,
			boolean isUnpacking, Date pasteTime, Date unpackingTime) {
		this.arrivalPlanDetails = arrivalPlanDetails;
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.damageDetails = damageDetails;
		this.goodsLocator = goodsLocator;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.loadPallets = loadPallets;
		this.pallets = pallets;
		this.storageAreas = storageAreas;
		this.storageRacks = storageRacks;
		this.userInfoByUnpackingUserId = userInfoByUnpackingUserId;
		this.userInfoByPasteUserId = userInfoByPasteUserId;
		this.warehouse = warehouse;
		this.goodsReceiptDetailsId = goodsReceiptDetailsId;
		this.sortingDetailsId = sortingDetailsId;
		this.receiptReturnDetailsId = receiptReturnDetailsId;
		this.palletsCode = palletsCode;
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.madeTime = madeTime;
		this.soonExpire = soonExpire;
		this.shelfLife = shelfLife;
		this.isDamage = isDamage;
		this.boxCode = boxCode;
		this.boxInQuantity = boxInQuantity;
		this.isUnpacking = isUnpacking;
		this.pasteTime = pasteTime;
		this.unpackingTime = unpackingTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stock_boxs_id", unique = true, nullable = false)
	public Integer getStockBoxsId() {
		return this.stockBoxsId;
	}

	public void setStockBoxsId(Integer stockBoxsId) {
		this.stockBoxsId = stockBoxsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "arrival_plan_details_id", nullable = false)
	public ArrivalPlanDetails getArrivalPlanDetails() {
		return this.arrivalPlanDetails;
	}

	public void setArrivalPlanDetails(ArrivalPlanDetails arrivalPlanDetails) {
		this.arrivalPlanDetails = arrivalPlanDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_base_id", nullable = false)
	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodityBase) {
		this.commodityBase = commodityBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_packing_id", nullable = false)
	public CommodityPacking getCommodityPacking() {
		return this.commodityPacking;
	}

	public void setCommodityPacking(CommodityPacking commodityPacking) {
		this.commodityPacking = commodityPacking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "damage_details_id")
	public DamageDetails getDamageDetails() {
		return this.damageDetails;
	}

	public void setDamageDetails(DamageDetails damageDetails) {
		this.damageDetails = damageDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_locator_id", nullable = false)
	public GoodsLocator getGoodsLocator() {
		return this.goodsLocator;
	}

	public void setGoodsLocator(GoodsLocator goodsLocator) {
		this.goodsLocator = goodsLocator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_commodity_id", nullable = false)
	public GoodsOwnerCommodity getGoodsOwnerCommodity() {
		return this.goodsOwnerCommodity;
	}

	public void setGoodsOwnerCommodity(GoodsOwnerCommodity goodsOwnerCommodity) {
		this.goodsOwnerCommodity = goodsOwnerCommodity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "load_pallets_id", nullable = false)
	public LoadPallets getLoadPallets() {
		return this.loadPallets;
	}

	public void setLoadPallets(LoadPallets loadPallets) {
		this.loadPallets = loadPallets;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pallets_id", nullable = false)
	public Pallets getPallets() {
		return this.pallets;
	}

	public void setPallets(Pallets pallets) {
		this.pallets = pallets;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storage_areas_id")
	public StorageAreas getStorageAreas() {
		return this.storageAreas;
	}

	public void setStorageAreas(StorageAreas storageAreas) {
		this.storageAreas = storageAreas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storage_racks_id")
	public StorageRacks getStorageRacks() {
		return this.storageRacks;
	}

	public void setStorageRacks(StorageRacks storageRacks) {
		this.storageRacks = storageRacks;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unpacking_user_id", nullable = false)
	public UserInfo getUserInfoByUnpackingUserId() {
		return this.userInfoByUnpackingUserId;
	}

	public void setUserInfoByUnpackingUserId(UserInfo userInfoByUnpackingUserId) {
		this.userInfoByUnpackingUserId = userInfoByUnpackingUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paste_user_id", nullable = false)
	public UserInfo getUserInfoByPasteUserId() {
		return this.userInfoByPasteUserId;
	}

	public void setUserInfoByPasteUserId(UserInfo userInfoByPasteUserId) {
		this.userInfoByPasteUserId = userInfoByPasteUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "warehouse_id", nullable = false)
	public Warehouse getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	@Column(name = "goods_receipt_details_id", nullable = false)
	public int getGoodsReceiptDetailsId() {
		return this.goodsReceiptDetailsId;
	}

	public void setGoodsReceiptDetailsId(int goodsReceiptDetailsId) {
		this.goodsReceiptDetailsId = goodsReceiptDetailsId;
	}

	@Column(name = "sorting_details_id")
	public Integer getSortingDetailsId() {
		return this.sortingDetailsId;
	}

	public void setSortingDetailsId(Integer sortingDetailsId) {
		this.sortingDetailsId = sortingDetailsId;
	}

	@Column(name = "receipt_return_details_id")
	public Integer getReceiptReturnDetailsId() {
		return this.receiptReturnDetailsId;
	}

	public void setReceiptReturnDetailsId(Integer receiptReturnDetailsId) {
		this.receiptReturnDetailsId = receiptReturnDetailsId;
	}

	@Column(name = "pallets_code", nullable = false, length = 13)
	public String getPalletsCode() {
		return this.palletsCode;
	}

	public void setPalletsCode(String palletsCode) {
		this.palletsCode = palletsCode;
	}

	@Column(name = "goods_owner_commodity_code", nullable = false, length = 20)
	public String getGoodsOwnerCommodityCode() {
		return this.goodsOwnerCommodityCode;
	}

	public void setGoodsOwnerCommodityCode(String goodsOwnerCommodityCode) {
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
	}

	@Column(name = "commodity_barcode", nullable = false, length = 20)
	public String getCommodityBarcode() {
		return this.commodityBarcode;
	}

	public void setCommodityBarcode(String commodityBarcode) {
		this.commodityBarcode = commodityBarcode;
	}

	@Column(name = "commodity_name", nullable = false, length = 50)
	public String getCommodityName() {
		return this.commodityName;
	}

	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	@Column(name = "commodity_standard", nullable = false, length = 50)
	public String getCommodityStandard() {
		return this.commodityStandard;
	}

	public void setCommodityStandard(String commodityStandard) {
		this.commodityStandard = commodityStandard;
	}

	@Column(name = "commodity_packing_unit", nullable = false, length = 10)
	public String getCommodityPackingUnit() {
		return this.commodityPackingUnit;
	}

	public void setCommodityPackingUnit(String commodityPackingUnit) {
		this.commodityPackingUnit = commodityPackingUnit;
	}

	@Column(name = "commodity_packing_quantity", nullable = false)
	public int getCommodityPackingQuantity() {
		return this.commodityPackingQuantity;
	}

	public void setCommodityPackingQuantity(int commodityPackingQuantity) {
		this.commodityPackingQuantity = commodityPackingQuantity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "made_time", nullable = false, length = 10)
	public Date getMadeTime() {
		return this.madeTime;
	}

	public void setMadeTime(Date madeTime) {
		this.madeTime = madeTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "soon_expire", nullable = false, length = 10)
	public Date getSoonExpire() {
		return this.soonExpire;
	}

	public void setSoonExpire(Date soonExpire) {
		this.soonExpire = soonExpire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "shelf_life", nullable = false, length = 10)
	public Date getShelfLife() {
		return this.shelfLife;
	}

	public void setShelfLife(Date shelfLife) {
		this.shelfLife = shelfLife;
	}

	@Column(name = "is_damage", nullable = false)
	public boolean isIsDamage() {
		return this.isDamage;
	}

	public void setIsDamage(boolean isDamage) {
		this.isDamage = isDamage;
	}

	@Column(name = "box_code", nullable = false, length = 20)
	public String getBoxCode() {
		return this.boxCode;
	}

	public void setBoxCode(String boxCode) {
		this.boxCode = boxCode;
	}

	@Column(name = "box_in_quantity", nullable = false)
	public int getBoxInQuantity() {
		return this.boxInQuantity;
	}

	public void setBoxInQuantity(int boxInQuantity) {
		this.boxInQuantity = boxInQuantity;
	}

	@Column(name = "is_unpacking", nullable = false)
	public boolean isIsUnpacking() {
		return this.isUnpacking;
	}

	public void setIsUnpacking(boolean isUnpacking) {
		this.isUnpacking = isUnpacking;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "paste_time", nullable = false, length = 19)
	public Date getPasteTime() {
		return this.pasteTime;
	}

	public void setPasteTime(Date pasteTime) {
		this.pasteTime = pasteTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "unpacking_time", nullable = false, length = 19)
	public Date getUnpackingTime() {
		return this.unpackingTime;
	}

	public void setUnpackingTime(Date unpackingTime) {
		this.unpackingTime = unpackingTime;
	}

}
