package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GoodsOwnerCommodity generated by hbm2java
 */
@Entity
@Table(name = "goods_owner_commodity", catalog = "sywm")
public class GoodsOwnerCommodity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer goodsOwnerCommodityId;
	private CommodityBase commodityBase;
	private CommodityPacking commodityPacking;
	private GoodsOwner goodsOwner;
	private String goodsOwnerCommodityCode;
	private String commodityBarcode;
	private String commodityName;
	private String commodityStandard;
	private String commodityPackingUnit;
	private int commodityPackingQuantity;
	private Set<ArrivalPlanDetails> arrivalPlanDetailses = new HashSet<ArrivalPlanDetails>(0);
	private Set<DeliverOrderDetails> deliverOrderDetailses = new HashSet<DeliverOrderDetails>(0);
	private Set<DamageInWarehouse> damageInWarehouses = new HashSet<DamageInWarehouse>(0);
	private Set<StockPallets> stockPalletses = new HashSet<StockPallets>(0);
	private Set<ReturnDetails> returnDetailses = new HashSet<ReturnDetails>(0);
	private Set<ReturnInWarehouse> returnInWarehouses = new HashSet<ReturnInWarehouse>(0);
	private Set<StockBoxs> stockBoxses = new HashSet<StockBoxs>(0);
	private Set<LoadPallets> loadPalletses = new HashSet<LoadPallets>(0);

	public GoodsOwnerCommodity() {
	}

	public GoodsOwnerCommodity(CommodityBase commodityBase, CommodityPacking commodityPacking, GoodsOwner goodsOwner,
			String commodityBarcode, String commodityName, String commodityStandard, String commodityPackingUnit,
			int commodityPackingQuantity) {
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.goodsOwner = goodsOwner;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
	}

	public GoodsOwnerCommodity(CommodityBase commodityBase, CommodityPacking commodityPacking, GoodsOwner goodsOwner,
			String goodsOwnerCommodityCode, String commodityBarcode, String commodityName, String commodityStandard,
			String commodityPackingUnit, int commodityPackingQuantity, Set<ArrivalPlanDetails> arrivalPlanDetailses,
			Set<DeliverOrderDetails> deliverOrderDetailses, Set<DamageInWarehouse> damageInWarehouses,
			Set<StockPallets> stockPalletses, Set<ReturnDetails> returnDetailses,
			Set<ReturnInWarehouse> returnInWarehouses, Set<StockBoxs> stockBoxses, Set<LoadPallets> loadPalletses) {
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.arrivalPlanDetailses = arrivalPlanDetailses;
		this.deliverOrderDetailses = deliverOrderDetailses;
		this.damageInWarehouses = damageInWarehouses;
		this.stockPalletses = stockPalletses;
		this.returnDetailses = returnDetailses;
		this.returnInWarehouses = returnInWarehouses;
		this.stockBoxses = stockBoxses;
		this.loadPalletses = loadPalletses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "goods_owner_commodity_id", unique = true, nullable = false)
	public Integer getGoodsOwnerCommodityId() {
		return this.goodsOwnerCommodityId;
	}

	public void setGoodsOwnerCommodityId(Integer goodsOwnerCommodityId) {
		this.goodsOwnerCommodityId = goodsOwnerCommodityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_base_id", nullable = false)
	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodityBase) {
		this.commodityBase = commodityBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_packing_id", nullable = false)
	public CommodityPacking getCommodityPacking() {
		return this.commodityPacking;
	}

	public void setCommodityPacking(CommodityPacking commodityPacking) {
		this.commodityPacking = commodityPacking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@Column(name = "goods_owner_commodity_code", length = 20)
	public String getGoodsOwnerCommodityCode() {
		return this.goodsOwnerCommodityCode;
	}

	public void setGoodsOwnerCommodityCode(String goodsOwnerCommodityCode) {
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
	}

	@Column(name = "commodity_barcode", nullable = false, length = 20)
	public String getCommodityBarcode() {
		return this.commodityBarcode;
	}

	public void setCommodityBarcode(String commodityBarcode) {
		this.commodityBarcode = commodityBarcode;
	}

	@Column(name = "commodity_name", nullable = false, length = 50)
	public String getCommodityName() {
		return this.commodityName;
	}

	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	@Column(name = "commodity_standard", nullable = false, length = 50)
	public String getCommodityStandard() {
		return this.commodityStandard;
	}

	public void setCommodityStandard(String commodityStandard) {
		this.commodityStandard = commodityStandard;
	}

	@Column(name = "commodity_packing_unit", nullable = false, length = 10)
	public String getCommodityPackingUnit() {
		return this.commodityPackingUnit;
	}

	public void setCommodityPackingUnit(String commodityPackingUnit) {
		this.commodityPackingUnit = commodityPackingUnit;
	}

	@Column(name = "commodity_packing_quantity", nullable = false)
	public int getCommodityPackingQuantity() {
		return this.commodityPackingQuantity;
	}

	public void setCommodityPackingQuantity(int commodityPackingQuantity) {
		this.commodityPackingQuantity = commodityPackingQuantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsOwnerCommodity")
	public Set<ArrivalPlanDetails> getArrivalPlanDetailses() {
		return this.arrivalPlanDetailses;
	}

	public void setArrivalPlanDetailses(Set<ArrivalPlanDetails> arrivalPlanDetailses) {
		this.arrivalPlanDetailses = arrivalPlanDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsOwnerCommodity")
	public Set<DeliverOrderDetails> getDeliverOrderDetailses() {
		return this.deliverOrderDetailses;
	}

	public void setDeliverOrderDetailses(Set<DeliverOrderDetails> deliverOrderDetailses) {
		this.deliverOrderDetailses = deliverOrderDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsOwnerCommodity")
	public Set<DamageInWarehouse> getDamageInWarehouses() {
		return this.damageInWarehouses;
	}

	public void setDamageInWarehouses(Set<DamageInWarehouse> damageInWarehouses) {
		this.damageInWarehouses = damageInWarehouses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsOwnerCommodity")
	public Set<StockPallets> getStockPalletses() {
		return this.stockPalletses;
	}

	public void setStockPalletses(Set<StockPallets> stockPalletses) {
		this.stockPalletses = stockPalletses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsOwnerCommodity")
	public Set<ReturnDetails> getReturnDetailses() {
		return this.returnDetailses;
	}

	public void setReturnDetailses(Set<ReturnDetails> returnDetailses) {
		this.returnDetailses = returnDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsOwnerCommodity")
	public Set<ReturnInWarehouse> getReturnInWarehouses() {
		return this.returnInWarehouses;
	}

	public void setReturnInWarehouses(Set<ReturnInWarehouse> returnInWarehouses) {
		this.returnInWarehouses = returnInWarehouses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsOwnerCommodity")
	public Set<StockBoxs> getStockBoxses() {
		return this.stockBoxses;
	}

	public void setStockBoxses(Set<StockBoxs> stockBoxses) {
		this.stockBoxses = stockBoxses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsOwnerCommodity")
	public Set<LoadPallets> getLoadPalletses() {
		return this.loadPalletses;
	}

	public void setLoadPalletses(Set<LoadPallets> loadPalletses) {
		this.loadPalletses = loadPalletses;
	}

}
