package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeliverOrderDetails generated by hbm2java
 */
@Entity
@Table(name = "deliver_order_details", catalog = "sywm")
public class DeliverOrderDetails implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer deliverOrderDetailsId;
	private CommodityBase commodityBase;
	private CommodityPacking commodityPacking;
	private DeliverOrder deliverOrder;
	private GoodsOwner goodsOwner;
	private GoodsOwnerCommodity goodsOwnerCommodity;
	private ShipInfo shipInfo;
	private String goodsOwnerCommodityCode;
	private String commodityBarcode;
	private String commodityName;
	private String commodityStandard;
	private String commodityPackingUnit;
	private int commodityPackingQuantity;
	private int saleQuantity;
	private BigDecimal saleUnitPrice;
	private BigDecimal salePrice;
	private Integer sortingQuantity;
	private Integer deliveryQuantity;
	private Boolean isReturn;
	private Integer returnQuantity;
	private Set<DeliverOrderBatchDetails> deliverOrderBatchDetailses = new HashSet<DeliverOrderBatchDetails>(0);
	private Set<DeliverOrderGiftDetails> deliverOrderGiftDetailses = new HashSet<DeliverOrderGiftDetails>(0);

	public DeliverOrderDetails() {
	}

	public DeliverOrderDetails(CommodityBase commodityBase, CommodityPacking commodityPacking,
			DeliverOrder deliverOrder, GoodsOwner goodsOwner, GoodsOwnerCommodity goodsOwnerCommodity,
			String commodityBarcode, String commodityName, String commodityStandard, String commodityPackingUnit,
			int commodityPackingQuantity, int saleQuantity, BigDecimal saleUnitPrice, BigDecimal salePrice) {
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.deliverOrder = deliverOrder;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.saleQuantity = saleQuantity;
		this.saleUnitPrice = saleUnitPrice;
		this.salePrice = salePrice;
	}

	public DeliverOrderDetails(CommodityBase commodityBase, CommodityPacking commodityPacking,
			DeliverOrder deliverOrder, GoodsOwner goodsOwner, GoodsOwnerCommodity goodsOwnerCommodity,
			ShipInfo shipInfo, String goodsOwnerCommodityCode, String commodityBarcode, String commodityName,
			String commodityStandard, String commodityPackingUnit, int commodityPackingQuantity, int saleQuantity,
			BigDecimal saleUnitPrice, BigDecimal salePrice, Integer sortingQuantity, Integer deliveryQuantity,
			Boolean isReturn, Integer returnQuantity, Set<DeliverOrderBatchDetails> deliverOrderBatchDetailses,
			Set<DeliverOrderGiftDetails> deliverOrderGiftDetailses) {
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.deliverOrder = deliverOrder;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.shipInfo = shipInfo;
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.saleQuantity = saleQuantity;
		this.saleUnitPrice = saleUnitPrice;
		this.salePrice = salePrice;
		this.sortingQuantity = sortingQuantity;
		this.deliveryQuantity = deliveryQuantity;
		this.isReturn = isReturn;
		this.returnQuantity = returnQuantity;
		this.deliverOrderBatchDetailses = deliverOrderBatchDetailses;
		this.deliverOrderGiftDetailses = deliverOrderGiftDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "deliver_order_details_id", unique = true, nullable = false)
	public Integer getDeliverOrderDetailsId() {
		return this.deliverOrderDetailsId;
	}

	public void setDeliverOrderDetailsId(Integer deliverOrderDetailsId) {
		this.deliverOrderDetailsId = deliverOrderDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_base_id", nullable = false)
	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodityBase) {
		this.commodityBase = commodityBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_packing_id", nullable = false)
	public CommodityPacking getCommodityPacking() {
		return this.commodityPacking;
	}

	public void setCommodityPacking(CommodityPacking commodityPacking) {
		this.commodityPacking = commodityPacking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deliver_order_id", nullable = false)
	public DeliverOrder getDeliverOrder() {
		return this.deliverOrder;
	}

	public void setDeliverOrder(DeliverOrder deliverOrder) {
		this.deliverOrder = deliverOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_commodity_id", nullable = false)
	public GoodsOwnerCommodity getGoodsOwnerCommodity() {
		return this.goodsOwnerCommodity;
	}

	public void setGoodsOwnerCommodity(GoodsOwnerCommodity goodsOwnerCommodity) {
		this.goodsOwnerCommodity = goodsOwnerCommodity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ship_info_id")
	public ShipInfo getShipInfo() {
		return this.shipInfo;
	}

	public void setShipInfo(ShipInfo shipInfo) {
		this.shipInfo = shipInfo;
	}

	@Column(name = "goods_owner_commodity_code", length = 20)
	public String getGoodsOwnerCommodityCode() {
		return this.goodsOwnerCommodityCode;
	}

	public void setGoodsOwnerCommodityCode(String goodsOwnerCommodityCode) {
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
	}

	@Column(name = "commodity_barcode", nullable = false, length = 20)
	public String getCommodityBarcode() {
		return this.commodityBarcode;
	}

	public void setCommodityBarcode(String commodityBarcode) {
		this.commodityBarcode = commodityBarcode;
	}

	@Column(name = "commodity_name", nullable = false, length = 50)
	public String getCommodityName() {
		return this.commodityName;
	}

	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	@Column(name = "commodity_standard", nullable = false, length = 50)
	public String getCommodityStandard() {
		return this.commodityStandard;
	}

	public void setCommodityStandard(String commodityStandard) {
		this.commodityStandard = commodityStandard;
	}

	@Column(name = "commodity_packing_unit", nullable = false, length = 10)
	public String getCommodityPackingUnit() {
		return this.commodityPackingUnit;
	}

	public void setCommodityPackingUnit(String commodityPackingUnit) {
		this.commodityPackingUnit = commodityPackingUnit;
	}

	@Column(name = "commodity_packing_quantity", nullable = false)
	public int getCommodityPackingQuantity() {
		return this.commodityPackingQuantity;
	}

	public void setCommodityPackingQuantity(int commodityPackingQuantity) {
		this.commodityPackingQuantity = commodityPackingQuantity;
	}

	@Column(name = "sale_quantity", nullable = false)
	public int getSaleQuantity() {
		return this.saleQuantity;
	}

	public void setSaleQuantity(int saleQuantity) {
		this.saleQuantity = saleQuantity;
	}

	@Column(name = "sale_unit_price", nullable = false, precision = 15)
	public BigDecimal getSaleUnitPrice() {
		return this.saleUnitPrice;
	}

	public void setSaleUnitPrice(BigDecimal saleUnitPrice) {
		this.saleUnitPrice = saleUnitPrice;
	}

	@Column(name = "sale_price", nullable = false, precision = 15)
	public BigDecimal getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

	@Column(name = "sorting_quantity")
	public Integer getSortingQuantity() {
		return this.sortingQuantity;
	}

	public void setSortingQuantity(Integer sortingQuantity) {
		this.sortingQuantity = sortingQuantity;
	}

	@Column(name = "delivery_quantity")
	public Integer getDeliveryQuantity() {
		return this.deliveryQuantity;
	}

	public void setDeliveryQuantity(Integer deliveryQuantity) {
		this.deliveryQuantity = deliveryQuantity;
	}

	@Column(name = "is_return")
	public Boolean getIsReturn() {
		return this.isReturn;
	}

	public void setIsReturn(Boolean isReturn) {
		this.isReturn = isReturn;
	}

	@Column(name = "return_quantity")
	public Integer getReturnQuantity() {
		return this.returnQuantity;
	}

	public void setReturnQuantity(Integer returnQuantity) {
		this.returnQuantity = returnQuantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deliverOrderDetails")
	public Set<DeliverOrderBatchDetails> getDeliverOrderBatchDetailses() {
		return this.deliverOrderBatchDetailses;
	}

	public void setDeliverOrderBatchDetailses(Set<DeliverOrderBatchDetails> deliverOrderBatchDetailses) {
		this.deliverOrderBatchDetailses = deliverOrderBatchDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deliverOrderDetails")
	public Set<DeliverOrderGiftDetails> getDeliverOrderGiftDetailses() {
		return this.deliverOrderGiftDetailses;
	}

	public void setDeliverOrderGiftDetailses(Set<DeliverOrderGiftDetails> deliverOrderGiftDetailses) {
		this.deliverOrderGiftDetailses = deliverOrderGiftDetailses;
	}

}
