package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brands generated by hbm2java
 */
@Entity
@Table(name = "brands", catalog = "sywm")
public class Brands implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer brandsId;
	private String brandsCode;
	private String brandsName;
	private boolean isDelete;
	private Set<CommodityBase> commodityBases = new HashSet<CommodityBase>(0);

	public Brands() {
	}

	public Brands(String brandsCode, String brandsName, boolean isDelete) {
		this.brandsCode = brandsCode;
		this.brandsName = brandsName;
		this.isDelete = isDelete;
	}

	public Brands(String brandsCode, String brandsName, boolean isDelete, Set<CommodityBase> commodityBases) {
		this.brandsCode = brandsCode;
		this.brandsName = brandsName;
		this.isDelete = isDelete;
		this.commodityBases = commodityBases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "brands_id", unique = true, nullable = false)
	public Integer getBrandsId() {
		return this.brandsId;
	}

	public void setBrandsId(Integer brandsId) {
		this.brandsId = brandsId;
	}

	@Column(name = "brands_code", nullable = false, length = 20)
	public String getBrandsCode() {
		return this.brandsCode;
	}

	public void setBrandsCode(String brandsCode) {
		this.brandsCode = brandsCode;
	}

	@Column(name = "brands_name", nullable = false, length = 50)
	public String getBrandsName() {
		return this.brandsName;
	}

	public void setBrandsName(String brandsName) {
		this.brandsName = brandsName;
	}

	@Column(name = "is_delete", nullable = false)
	public boolean isIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brands")
	public Set<CommodityBase> getCommodityBases() {
		return this.commodityBases;
	}

	public void setCommodityBases(Set<CommodityBase> commodityBases) {
		this.commodityBases = commodityBases;
	}

}
