package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Damage generated by hbm2java
 */
@Entity
@Table(name = "damage", catalog = "sywm")
public class Damage implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer damageId;
	private GoodsOwner goodsOwner;
	private GoodsOwnerUser goodsOwnerUser;
	private UserInfo userInfo;
	private String damageCode;
	private int damageLink;
	private Date createTime;
	private Date confirmTime;
	private String damageExplain;
	private int damageStatus;
	private boolean isDelete;
	private Set<DamageDetails> damageDetailses = new HashSet<DamageDetails>(0);

	public Damage() {
	}

	public Damage(GoodsOwner goodsOwner, UserInfo userInfo, String damageCode, int damageLink, Date createTime,
			int damageStatus, boolean isDelete) {
		this.goodsOwner = goodsOwner;
		this.userInfo = userInfo;
		this.damageCode = damageCode;
		this.damageLink = damageLink;
		this.createTime = createTime;
		this.damageStatus = damageStatus;
		this.isDelete = isDelete;
	}

	public Damage(GoodsOwner goodsOwner, GoodsOwnerUser goodsOwnerUser, UserInfo userInfo, String damageCode,
			int damageLink, Date createTime, Date confirmTime, String damageExplain, int damageStatus, boolean isDelete,
			Set<DamageDetails> damageDetailses) {
		this.goodsOwner = goodsOwner;
		this.goodsOwnerUser = goodsOwnerUser;
		this.userInfo = userInfo;
		this.damageCode = damageCode;
		this.damageLink = damageLink;
		this.createTime = createTime;
		this.confirmTime = confirmTime;
		this.damageExplain = damageExplain;
		this.damageStatus = damageStatus;
		this.isDelete = isDelete;
		this.damageDetailses = damageDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "damage_id", unique = true, nullable = false)
	public Integer getDamageId() {
		return this.damageId;
	}

	public void setDamageId(Integer damageId) {
		this.damageId = damageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_user_id")
	public GoodsOwnerUser getGoodsOwnerUser() {
		return this.goodsOwnerUser;
	}

	public void setGoodsOwnerUser(GoodsOwnerUser goodsOwnerUser) {
		this.goodsOwnerUser = goodsOwnerUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_info_id", nullable = false)
	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	@Column(name = "damage_code", nullable = false, length = 14)
	public String getDamageCode() {
		return this.damageCode;
	}

	public void setDamageCode(String damageCode) {
		this.damageCode = damageCode;
	}

	@Column(name = "damage_link", nullable = false)
	public int getDamageLink() {
		return this.damageLink;
	}

	public void setDamageLink(int damageLink) {
		this.damageLink = damageLink;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "confirm_time", length = 19)
	public Date getConfirmTime() {
		return this.confirmTime;
	}

	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}

	@Column(name = "damage_explain", length = 50)
	public String getDamageExplain() {
		return this.damageExplain;
	}

	public void setDamageExplain(String damageExplain) {
		this.damageExplain = damageExplain;
	}

	@Column(name = "damage_status", nullable = false)
	public int getDamageStatus() {
		return this.damageStatus;
	}

	public void setDamageStatus(int damageStatus) {
		this.damageStatus = damageStatus;
	}

	@Column(name = "is_delete", nullable = false)
	public boolean isIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "damage")
	public Set<DamageDetails> getDamageDetailses() {
		return this.damageDetailses;
	}

	public void setDamageDetailses(Set<DamageDetails> damageDetailses) {
		this.damageDetailses = damageDetailses;
	}

}
