package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StorageRacks generated by hbm2java
 */
@Entity
@Table(name = "storage_racks", catalog = "sywm")
public class StorageRacks implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer storageRacksId;
	private StorageAreas storageAreas;
	private Warehouse warehouse;
	private String storageRacksCode;
	private int storageRacksType;
	private BigDecimal goodsLocatorCount;
	private Integer displayRow;
	private Integer displayColumn;
	private Boolean isDisplay;
	private BigDecimal storageRacksLength;
	private BigDecimal storageRacksWidth;
	private BigDecimal storageRacksHeight;
	private BigDecimal storageRacksArea;
	private boolean isEnable;
	private Set<StockBoxs> stockBoxses = new HashSet<StockBoxs>(0);
	private Set<GoodsLocator> goodsLocators = new HashSet<GoodsLocator>(0);
	private Set<StockPallets> stockPalletses = new HashSet<StockPallets>(0);

	public StorageRacks() {
	}

	public StorageRacks(Warehouse warehouse, String storageRacksCode, int storageRacksType,
			BigDecimal goodsLocatorCount, boolean isEnable) {
		this.warehouse = warehouse;
		this.storageRacksCode = storageRacksCode;
		this.storageRacksType = storageRacksType;
		this.goodsLocatorCount = goodsLocatorCount;
		this.isEnable = isEnable;
	}

	public StorageRacks(StorageAreas storageAreas, Warehouse warehouse, String storageRacksCode, int storageRacksType,
			BigDecimal goodsLocatorCount, Integer displayRow, Integer displayColumn, Boolean isDisplay,
			BigDecimal storageRacksLength, BigDecimal storageRacksWidth, BigDecimal storageRacksHeight,
			BigDecimal storageRacksArea, boolean isEnable, Set<StockBoxs> stockBoxses, Set<GoodsLocator> goodsLocators,
			Set<StockPallets> stockPalletses) {
		this.storageAreas = storageAreas;
		this.warehouse = warehouse;
		this.storageRacksCode = storageRacksCode;
		this.storageRacksType = storageRacksType;
		this.goodsLocatorCount = goodsLocatorCount;
		this.displayRow = displayRow;
		this.displayColumn = displayColumn;
		this.isDisplay = isDisplay;
		this.storageRacksLength = storageRacksLength;
		this.storageRacksWidth = storageRacksWidth;
		this.storageRacksHeight = storageRacksHeight;
		this.storageRacksArea = storageRacksArea;
		this.isEnable = isEnable;
		this.stockBoxses = stockBoxses;
		this.goodsLocators = goodsLocators;
		this.stockPalletses = stockPalletses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "storage_racks_id", unique = true, nullable = false)
	public Integer getStorageRacksId() {
		return this.storageRacksId;
	}

	public void setStorageRacksId(Integer storageRacksId) {
		this.storageRacksId = storageRacksId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storage_areas_id")
	public StorageAreas getStorageAreas() {
		return this.storageAreas;
	}

	public void setStorageAreas(StorageAreas storageAreas) {
		this.storageAreas = storageAreas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "warehouse_id", nullable = false)
	public Warehouse getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	@Column(name = "storage_racks_code", nullable = false, length = 10)
	public String getStorageRacksCode() {
		return this.storageRacksCode;
	}

	public void setStorageRacksCode(String storageRacksCode) {
		this.storageRacksCode = storageRacksCode;
	}

	@Column(name = "storage_racks_type", nullable = false)
	public int getStorageRacksType() {
		return this.storageRacksType;
	}

	public void setStorageRacksType(int storageRacksType) {
		this.storageRacksType = storageRacksType;
	}

	@Column(name = "goods_locator_count", nullable = false, precision = 3, scale = 1)
	public BigDecimal getGoodsLocatorCount() {
		return this.goodsLocatorCount;
	}

	public void setGoodsLocatorCount(BigDecimal goodsLocatorCount) {
		this.goodsLocatorCount = goodsLocatorCount;
	}

	@Column(name = "display_row")
	public Integer getDisplayRow() {
		return this.displayRow;
	}

	public void setDisplayRow(Integer displayRow) {
		this.displayRow = displayRow;
	}

	@Column(name = "display_column")
	public Integer getDisplayColumn() {
		return this.displayColumn;
	}

	public void setDisplayColumn(Integer displayColumn) {
		this.displayColumn = displayColumn;
	}

	@Column(name = "is_display")
	public Boolean getIsDisplay() {
		return this.isDisplay;
	}

	public void setIsDisplay(Boolean isDisplay) {
		this.isDisplay = isDisplay;
	}

	@Column(name = "storage_racks_length", precision = 6)
	public BigDecimal getStorageRacksLength() {
		return this.storageRacksLength;
	}

	public void setStorageRacksLength(BigDecimal storageRacksLength) {
		this.storageRacksLength = storageRacksLength;
	}

	@Column(name = "storage_racks_width", precision = 6)
	public BigDecimal getStorageRacksWidth() {
		return this.storageRacksWidth;
	}

	public void setStorageRacksWidth(BigDecimal storageRacksWidth) {
		this.storageRacksWidth = storageRacksWidth;
	}

	@Column(name = "storage_racks_height", precision = 6)
	public BigDecimal getStorageRacksHeight() {
		return this.storageRacksHeight;
	}

	public void setStorageRacksHeight(BigDecimal storageRacksHeight) {
		this.storageRacksHeight = storageRacksHeight;
	}

	@Column(name = "storage_racks_area", precision = 11, scale = 3)
	public BigDecimal getStorageRacksArea() {
		return this.storageRacksArea;
	}

	public void setStorageRacksArea(BigDecimal storageRacksArea) {
		this.storageRacksArea = storageRacksArea;
	}

	@Column(name = "is_enable", nullable = false)
	public boolean isIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(boolean isEnable) {
		this.isEnable = isEnable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storageRacks")
	public Set<StockBoxs> getStockBoxses() {
		return this.stockBoxses;
	}

	public void setStockBoxses(Set<StockBoxs> stockBoxses) {
		this.stockBoxses = stockBoxses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storageRacks")
	public Set<GoodsLocator> getGoodsLocators() {
		return this.goodsLocators;
	}

	public void setGoodsLocators(Set<GoodsLocator> goodsLocators) {
		this.goodsLocators = goodsLocators;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storageRacks")
	public Set<StockPallets> getStockPalletses() {
		return this.stockPalletses;
	}

	public void setStockPalletses(Set<StockPallets> stockPalletses) {
		this.stockPalletses = stockPalletses;
	}

}
