package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SystemFunction generated by hbm2java
 */
@Entity
@Table(name = "system_function", catalog = "sywm")
public class SystemFunction implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer systemFunctionId;
	private int systemFunctionParentId;
	private String systemFunctionName;
	private String systemFunctionUrl;
	private Integer systemFunctionSort;
	private String systemFunctionIcon;
	private String systemFunctionDescribe;
	private boolean isShow;
	private Set<UserAuth> userAuths = new HashSet<UserAuth>(0);

	public SystemFunction() {
	}

	public SystemFunction(int systemFunctionParentId, boolean isShow) {
		this.systemFunctionParentId = systemFunctionParentId;
		this.isShow = isShow;
	}

	public SystemFunction(int systemFunctionParentId, String systemFunctionName, String systemFunctionUrl,
			Integer systemFunctionSort, String systemFunctionIcon, String systemFunctionDescribe, boolean isShow,
			Set<UserAuth> userAuths) {
		this.systemFunctionParentId = systemFunctionParentId;
		this.systemFunctionName = systemFunctionName;
		this.systemFunctionUrl = systemFunctionUrl;
		this.systemFunctionSort = systemFunctionSort;
		this.systemFunctionIcon = systemFunctionIcon;
		this.systemFunctionDescribe = systemFunctionDescribe;
		this.isShow = isShow;
		this.userAuths = userAuths;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "system_function_id", unique = true, nullable = false)
	public Integer getSystemFunctionId() {
		return this.systemFunctionId;
	}

	public void setSystemFunctionId(Integer systemFunctionId) {
		this.systemFunctionId = systemFunctionId;
	}

	@Column(name = "system_function_parent_id", nullable = false)
	public int getSystemFunctionParentId() {
		return this.systemFunctionParentId;
	}

	public void setSystemFunctionParentId(int systemFunctionParentId) {
		this.systemFunctionParentId = systemFunctionParentId;
	}

	@Column(name = "system_function_name", length = 50)
	public String getSystemFunctionName() {
		return this.systemFunctionName;
	}

	public void setSystemFunctionName(String systemFunctionName) {
		this.systemFunctionName = systemFunctionName;
	}

	@Column(name = "system_function_url", length = 100)
	public String getSystemFunctionUrl() {
		return this.systemFunctionUrl;
	}

	public void setSystemFunctionUrl(String systemFunctionUrl) {
		this.systemFunctionUrl = systemFunctionUrl;
	}

	@Column(name = "system_function_sort")
	public Integer getSystemFunctionSort() {
		return this.systemFunctionSort;
	}

	public void setSystemFunctionSort(Integer systemFunctionSort) {
		this.systemFunctionSort = systemFunctionSort;
	}

	@Column(name = "system_function_icon", length = 100)
	public String getSystemFunctionIcon() {
		return this.systemFunctionIcon;
	}

	public void setSystemFunctionIcon(String systemFunctionIcon) {
		this.systemFunctionIcon = systemFunctionIcon;
	}

	@Column(name = "system_function_describe", length = 200)
	public String getSystemFunctionDescribe() {
		return this.systemFunctionDescribe;
	}

	public void setSystemFunctionDescribe(String systemFunctionDescribe) {
		this.systemFunctionDescribe = systemFunctionDescribe;
	}

	@Column(name = "is_show", nullable = false)
	public boolean isIsShow() {
		return this.isShow;
	}

	public void setIsShow(boolean isShow) {
		this.isShow = isShow;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemFunction")
	public Set<UserAuth> getUserAuths() {
		return this.userAuths;
	}

	public void setUserAuths(Set<UserAuth> userAuths) {
		this.userAuths = userAuths;
	}

}
