package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DamageDetails generated by hbm2java
 */
@Entity
@Table(name = "damage_details", catalog = "sywm")
public class DamageDetails implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer damageDetailsId;
	private CommodityBase commodityBase;
	private CommodityPacking commodityPacking;
	private Damage damage;
	private GoodsLocator goodsLocator;
	private GoodsOwner goodsOwner;
	private Pallets pallets;
	private ReturnDetails returnDetails;
	private String commodityCode;
	private String commodityName;
	private String commodityStandard;
	private int commodityQuantity;
	private String commodityPackingUnit;
	private Integer commodityPackingQuantity;
	private Integer goodsReceiptDetailsId;
	private String palletsCode;
	private String locatorCode;
	private boolean isInWarehouse;
	private Date madeTime;
	private Date soonExpire;
	private Set<StockBoxs> stockBoxses = new HashSet<StockBoxs>(0);
	private Set<DamageInWarehouse> damageInWarehouses = new HashSet<DamageInWarehouse>(0);

	public DamageDetails() {
	}

	public DamageDetails(CommodityBase commodityBase, Damage damage, GoodsOwner goodsOwner, String commodityCode,
			String commodityName, String commodityStandard, int commodityQuantity, boolean isInWarehouse) {
		this.commodityBase = commodityBase;
		this.damage = damage;
		this.goodsOwner = goodsOwner;
		this.commodityCode = commodityCode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityQuantity = commodityQuantity;
		this.isInWarehouse = isInWarehouse;
	}

	public DamageDetails(CommodityBase commodityBase, CommodityPacking commodityPacking, Damage damage,
			GoodsLocator goodsLocator, GoodsOwner goodsOwner, Pallets pallets, ReturnDetails returnDetails,
			String commodityCode, String commodityName, String commodityStandard, int commodityQuantity,
			String commodityPackingUnit, Integer commodityPackingQuantity, Integer goodsReceiptDetailsId,
			String palletsCode, String locatorCode, boolean isInWarehouse, Date madeTime, Date soonExpire,
			Set<StockBoxs> stockBoxses, Set<DamageInWarehouse> damageInWarehouses) {
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.damage = damage;
		this.goodsLocator = goodsLocator;
		this.goodsOwner = goodsOwner;
		this.pallets = pallets;
		this.returnDetails = returnDetails;
		this.commodityCode = commodityCode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityQuantity = commodityQuantity;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.goodsReceiptDetailsId = goodsReceiptDetailsId;
		this.palletsCode = palletsCode;
		this.locatorCode = locatorCode;
		this.isInWarehouse = isInWarehouse;
		this.madeTime = madeTime;
		this.soonExpire = soonExpire;
		this.stockBoxses = stockBoxses;
		this.damageInWarehouses = damageInWarehouses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "damage_details_id", unique = true, nullable = false)
	public Integer getDamageDetailsId() {
		return this.damageDetailsId;
	}

	public void setDamageDetailsId(Integer damageDetailsId) {
		this.damageDetailsId = damageDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_base_id", nullable = false)
	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodityBase) {
		this.commodityBase = commodityBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_packing_id")
	public CommodityPacking getCommodityPacking() {
		return this.commodityPacking;
	}

	public void setCommodityPacking(CommodityPacking commodityPacking) {
		this.commodityPacking = commodityPacking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "damage_id", nullable = false)
	public Damage getDamage() {
		return this.damage;
	}

	public void setDamage(Damage damage) {
		this.damage = damage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_locator_id")
	public GoodsLocator getGoodsLocator() {
		return this.goodsLocator;
	}

	public void setGoodsLocator(GoodsLocator goodsLocator) {
		this.goodsLocator = goodsLocator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pallets_id")
	public Pallets getPallets() {
		return this.pallets;
	}

	public void setPallets(Pallets pallets) {
		this.pallets = pallets;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "return_details_id")
	public ReturnDetails getReturnDetails() {
		return this.returnDetails;
	}

	public void setReturnDetails(ReturnDetails returnDetails) {
		this.returnDetails = returnDetails;
	}

	@Column(name = "commodity_code", nullable = false, length = 20)
	public String getCommodityCode() {
		return this.commodityCode;
	}

	public void setCommodityCode(String commodityCode) {
		this.commodityCode = commodityCode;
	}

	@Column(name = "commodity_name", nullable = false, length = 50)
	public String getCommodityName() {
		return this.commodityName;
	}

	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	@Column(name = "commodity_standard", nullable = false, length = 50)
	public String getCommodityStandard() {
		return this.commodityStandard;
	}

	public void setCommodityStandard(String commodityStandard) {
		this.commodityStandard = commodityStandard;
	}

	@Column(name = "commodity_quantity", nullable = false)
	public int getCommodityQuantity() {
		return this.commodityQuantity;
	}

	public void setCommodityQuantity(int commodityQuantity) {
		this.commodityQuantity = commodityQuantity;
	}

	@Column(name = "commodity_packing_unit", length = 10)
	public String getCommodityPackingUnit() {
		return this.commodityPackingUnit;
	}

	public void setCommodityPackingUnit(String commodityPackingUnit) {
		this.commodityPackingUnit = commodityPackingUnit;
	}

	@Column(name = "commodity_packing_quantity")
	public Integer getCommodityPackingQuantity() {
		return this.commodityPackingQuantity;
	}

	public void setCommodityPackingQuantity(Integer commodityPackingQuantity) {
		this.commodityPackingQuantity = commodityPackingQuantity;
	}

	@Column(name = "goods_receipt_details_id")
	public Integer getGoodsReceiptDetailsId() {
		return this.goodsReceiptDetailsId;
	}

	public void setGoodsReceiptDetailsId(Integer goodsReceiptDetailsId) {
		this.goodsReceiptDetailsId = goodsReceiptDetailsId;
	}

	@Column(name = "pallets_code", length = 13)
	public String getPalletsCode() {
		return this.palletsCode;
	}

	public void setPalletsCode(String palletsCode) {
		this.palletsCode = palletsCode;
	}

	@Column(name = "locator_code", length = 50)
	public String getLocatorCode() {
		return this.locatorCode;
	}

	public void setLocatorCode(String locatorCode) {
		this.locatorCode = locatorCode;
	}

	@Column(name = "is_in_warehouse", nullable = false)
	public boolean isIsInWarehouse() {
		return this.isInWarehouse;
	}

	public void setIsInWarehouse(boolean isInWarehouse) {
		this.isInWarehouse = isInWarehouse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "made_time", length = 10)
	public Date getMadeTime() {
		return this.madeTime;
	}

	public void setMadeTime(Date madeTime) {
		this.madeTime = madeTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "soon_expire", length = 10)
	public Date getSoonExpire() {
		return this.soonExpire;
	}

	public void setSoonExpire(Date soonExpire) {
		this.soonExpire = soonExpire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "damageDetails")
	public Set<StockBoxs> getStockBoxses() {
		return this.stockBoxses;
	}

	public void setStockBoxses(Set<StockBoxs> stockBoxses) {
		this.stockBoxses = stockBoxses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "damageDetails")
	public Set<DamageInWarehouse> getDamageInWarehouses() {
		return this.damageInWarehouses;
	}

	public void setDamageInWarehouses(Set<DamageInWarehouse> damageInWarehouses) {
		this.damageInWarehouses = damageInWarehouses;
	}

}
