package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pallets generated by hbm2java
 */
@Entity
@Table(name = "pallets", catalog = "sywm")
public class Pallets implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer palletsId;
	private GoodsLocator goodsLocator;
	private String makerCode;
	private String makerName;
	private Integer palletsType;
	private String madeTime;
	private String palletsCode;
	private Integer palletsProperty;
	private boolean isEnable;
	private Set<LoadPallets> loadPalletses = new HashSet<LoadPallets>(0);
	private Set<StockPallets> stockPalletses = new HashSet<StockPallets>(0);
	private Set<DamageDetails> damageDetailses = new HashSet<DamageDetails>(0);
	private Set<StockBoxs> stockBoxses = new HashSet<StockBoxs>(0);
	private Set<DamageInWarehouse> damageInWarehouses = new HashSet<DamageInWarehouse>(0);
	private Set<ReturnInWarehouse> returnInWarehouses = new HashSet<ReturnInWarehouse>(0);

	public Pallets() {
	}

	public Pallets(String makerCode, String makerName, String madeTime, String palletsCode, boolean isEnable) {
		this.makerCode = makerCode;
		this.makerName = makerName;
		this.madeTime = madeTime;
		this.palletsCode = palletsCode;
		this.isEnable = isEnable;
	}

	public Pallets(GoodsLocator goodsLocator, String makerCode, String makerName, Integer palletsType, String madeTime,
			String palletsCode, Integer palletsProperty, boolean isEnable, Set<LoadPallets> loadPalletses,
			Set<StockPallets> stockPalletses, Set<DamageDetails> damageDetailses, Set<StockBoxs> stockBoxses,
			Set<DamageInWarehouse> damageInWarehouses, Set<ReturnInWarehouse> returnInWarehouses) {
		this.goodsLocator = goodsLocator;
		this.makerCode = makerCode;
		this.makerName = makerName;
		this.palletsType = palletsType;
		this.madeTime = madeTime;
		this.palletsCode = palletsCode;
		this.palletsProperty = palletsProperty;
		this.isEnable = isEnable;
		this.loadPalletses = loadPalletses;
		this.stockPalletses = stockPalletses;
		this.damageDetailses = damageDetailses;
		this.stockBoxses = stockBoxses;
		this.damageInWarehouses = damageInWarehouses;
		this.returnInWarehouses = returnInWarehouses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pallets_id", unique = true, nullable = false)
	public Integer getPalletsId() {
		return this.palletsId;
	}

	public void setPalletsId(Integer palletsId) {
		this.palletsId = palletsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_locator_id")
	public GoodsLocator getGoodsLocator() {
		return this.goodsLocator;
	}

	public void setGoodsLocator(GoodsLocator goodsLocator) {
		this.goodsLocator = goodsLocator;
	}

	@Column(name = "maker_code", nullable = false, length = 2)
	public String getMakerCode() {
		return this.makerCode;
	}

	public void setMakerCode(String makerCode) {
		this.makerCode = makerCode;
	}

	@Column(name = "maker_name", nullable = false, length = 50)
	public String getMakerName() {
		return this.makerName;
	}

	public void setMakerName(String makerName) {
		this.makerName = makerName;
	}

	@Column(name = "pallets_type")
	public Integer getPalletsType() {
		return this.palletsType;
	}

	public void setPalletsType(Integer palletsType) {
		this.palletsType = palletsType;
	}

	@Column(name = "made_time", nullable = false, length = 8)
	public String getMadeTime() {
		return this.madeTime;
	}

	public void setMadeTime(String madeTime) {
		this.madeTime = madeTime;
	}

	@Column(name = "pallets_code", nullable = false, length = 13)
	public String getPalletsCode() {
		return this.palletsCode;
	}

	public void setPalletsCode(String palletsCode) {
		this.palletsCode = palletsCode;
	}

	@Column(name = "pallets_property")
	public Integer getPalletsProperty() {
		return this.palletsProperty;
	}

	public void setPalletsProperty(Integer palletsProperty) {
		this.palletsProperty = palletsProperty;
	}

	@Column(name = "is_enable", nullable = false)
	public boolean isIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(boolean isEnable) {
		this.isEnable = isEnable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pallets")
	public Set<LoadPallets> getLoadPalletses() {
		return this.loadPalletses;
	}

	public void setLoadPalletses(Set<LoadPallets> loadPalletses) {
		this.loadPalletses = loadPalletses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pallets")
	public Set<StockPallets> getStockPalletses() {
		return this.stockPalletses;
	}

	public void setStockPalletses(Set<StockPallets> stockPalletses) {
		this.stockPalletses = stockPalletses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pallets")
	public Set<DamageDetails> getDamageDetailses() {
		return this.damageDetailses;
	}

	public void setDamageDetailses(Set<DamageDetails> damageDetailses) {
		this.damageDetailses = damageDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pallets")
	public Set<StockBoxs> getStockBoxses() {
		return this.stockBoxses;
	}

	public void setStockBoxses(Set<StockBoxs> stockBoxses) {
		this.stockBoxses = stockBoxses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pallets")
	public Set<DamageInWarehouse> getDamageInWarehouses() {
		return this.damageInWarehouses;
	}

	public void setDamageInWarehouses(Set<DamageInWarehouse> damageInWarehouses) {
		this.damageInWarehouses = damageInWarehouses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pallets")
	public Set<ReturnInWarehouse> getReturnInWarehouses() {
		return this.returnInWarehouses;
	}

	public void setReturnInWarehouses(Set<ReturnInWarehouse> returnInWarehouses) {
		this.returnInWarehouses = returnInWarehouses;
	}

}
