package com.rescam.sywm.server.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoadPallets generated by hbm2java
 */
@Entity
@Table(name = "load_pallets", catalog = "sywm")
public class LoadPallets implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer loadPalletsId;
	private ArrivalPlanDetails arrivalPlanDetails;
	private CommodityBase commodityBase;
	private CommodityPacking commodityPacking;
	private GoodsLocator goodsLocator;
	private GoodsOwner goodsOwner;
	private GoodsOwnerCommodity goodsOwnerCommodity;
	private Pallets pallets;
	private UserInfo userInfoByStackingUserId;
	private UserInfo userInfoByLoadPalletsUserId;
	private Warehouse warehouse;
	private String palletsCode;
	private String goodsOwnerCommodityCode;
	private String commodityBarcode;
	private String commodityName;
	private String commodityStandard;
	private String commodityPackingUnit;
	private int commodityPackingQuantity;
	private int loadPalletsQuantity;
	private Date madeTime;
	private Date soonExpire;
	private Date shelfLife;
	private Date loadPalletsTime;
	private String locatorCode;
	private Date stackingDatetime;
	private Set<StockPallets> stockPalletses = new HashSet<StockPallets>(0);
	private Set<StockBoxs> stockBoxses = new HashSet<StockBoxs>(0);

	public LoadPallets() {
	}

	public LoadPallets(CommodityBase commodityBase, CommodityPacking commodityPacking, GoodsOwner goodsOwner,
			GoodsOwnerCommodity goodsOwnerCommodity, Pallets pallets, UserInfo userInfoByLoadPalletsUserId,
			String palletsCode, String commodityBarcode, String commodityName, String commodityStandard,
			String commodityPackingUnit, int commodityPackingQuantity, int loadPalletsQuantity, Date madeTime,
			Date soonExpire, Date shelfLife, Date loadPalletsTime) {
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.pallets = pallets;
		this.userInfoByLoadPalletsUserId = userInfoByLoadPalletsUserId;
		this.palletsCode = palletsCode;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.loadPalletsQuantity = loadPalletsQuantity;
		this.madeTime = madeTime;
		this.soonExpire = soonExpire;
		this.shelfLife = shelfLife;
		this.loadPalletsTime = loadPalletsTime;
	}

	public LoadPallets(ArrivalPlanDetails arrivalPlanDetails, CommodityBase commodityBase,
			CommodityPacking commodityPacking, GoodsLocator goodsLocator, GoodsOwner goodsOwner,
			GoodsOwnerCommodity goodsOwnerCommodity, Pallets pallets, UserInfo userInfoByStackingUserId,
			UserInfo userInfoByLoadPalletsUserId, Warehouse warehouse, String palletsCode,
			String goodsOwnerCommodityCode, String commodityBarcode, String commodityName, String commodityStandard,
			String commodityPackingUnit, int commodityPackingQuantity, int loadPalletsQuantity, Date madeTime,
			Date soonExpire, Date shelfLife, Date loadPalletsTime, String locatorCode, Date stackingDatetime,
			Set<StockPallets> stockPalletses, Set<StockBoxs> stockBoxses) {
		this.arrivalPlanDetails = arrivalPlanDetails;
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.goodsLocator = goodsLocator;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.pallets = pallets;
		this.userInfoByStackingUserId = userInfoByStackingUserId;
		this.userInfoByLoadPalletsUserId = userInfoByLoadPalletsUserId;
		this.warehouse = warehouse;
		this.palletsCode = palletsCode;
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.loadPalletsQuantity = loadPalletsQuantity;
		this.madeTime = madeTime;
		this.soonExpire = soonExpire;
		this.shelfLife = shelfLife;
		this.loadPalletsTime = loadPalletsTime;
		this.locatorCode = locatorCode;
		this.stackingDatetime = stackingDatetime;
		this.stockPalletses = stockPalletses;
		this.stockBoxses = stockBoxses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "load_pallets_id", unique = true, nullable = false)
	public Integer getLoadPalletsId() {
		return this.loadPalletsId;
	}

	public void setLoadPalletsId(Integer loadPalletsId) {
		this.loadPalletsId = loadPalletsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "arrival_plan_details_id")
	public ArrivalPlanDetails getArrivalPlanDetails() {
		return this.arrivalPlanDetails;
	}

	public void setArrivalPlanDetails(ArrivalPlanDetails arrivalPlanDetails) {
		this.arrivalPlanDetails = arrivalPlanDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_base_id", nullable = false)
	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodityBase) {
		this.commodityBase = commodityBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_packing_id", nullable = false)
	public CommodityPacking getCommodityPacking() {
		return this.commodityPacking;
	}

	public void setCommodityPacking(CommodityPacking commodityPacking) {
		this.commodityPacking = commodityPacking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_locator_id")
	public GoodsLocator getGoodsLocator() {
		return this.goodsLocator;
	}

	public void setGoodsLocator(GoodsLocator goodsLocator) {
		this.goodsLocator = goodsLocator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_commodity_id", nullable = false)
	public GoodsOwnerCommodity getGoodsOwnerCommodity() {
		return this.goodsOwnerCommodity;
	}

	public void setGoodsOwnerCommodity(GoodsOwnerCommodity goodsOwnerCommodity) {
		this.goodsOwnerCommodity = goodsOwnerCommodity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pallets_id", nullable = false)
	public Pallets getPallets() {
		return this.pallets;
	}

	public void setPallets(Pallets pallets) {
		this.pallets = pallets;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stacking_user_id")
	public UserInfo getUserInfoByStackingUserId() {
		return this.userInfoByStackingUserId;
	}

	public void setUserInfoByStackingUserId(UserInfo userInfoByStackingUserId) {
		this.userInfoByStackingUserId = userInfoByStackingUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "load_pallets_user_id", nullable = false)
	public UserInfo getUserInfoByLoadPalletsUserId() {
		return this.userInfoByLoadPalletsUserId;
	}

	public void setUserInfoByLoadPalletsUserId(UserInfo userInfoByLoadPalletsUserId) {
		this.userInfoByLoadPalletsUserId = userInfoByLoadPalletsUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "warehouse_id")
	public Warehouse getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	@Column(name = "pallets_code", nullable = false, length = 13)
	public String getPalletsCode() {
		return this.palletsCode;
	}

	public void setPalletsCode(String palletsCode) {
		this.palletsCode = palletsCode;
	}

	@Column(name = "goods_owner_commodity_code", length = 20)
	public String getGoodsOwnerCommodityCode() {
		return this.goodsOwnerCommodityCode;
	}

	public void setGoodsOwnerCommodityCode(String goodsOwnerCommodityCode) {
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
	}

	@Column(name = "commodity_barcode", nullable = false, length = 20)
	public String getCommodityBarcode() {
		return this.commodityBarcode;
	}

	public void setCommodityBarcode(String commodityBarcode) {
		this.commodityBarcode = commodityBarcode;
	}

	@Column(name = "commodity_name", nullable = false, length = 50)
	public String getCommodityName() {
		return this.commodityName;
	}

	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	@Column(name = "commodity_standard", nullable = false, length = 50)
	public String getCommodityStandard() {
		return this.commodityStandard;
	}

	public void setCommodityStandard(String commodityStandard) {
		this.commodityStandard = commodityStandard;
	}

	@Column(name = "commodity_packing_unit", nullable = false, length = 10)
	public String getCommodityPackingUnit() {
		return this.commodityPackingUnit;
	}

	public void setCommodityPackingUnit(String commodityPackingUnit) {
		this.commodityPackingUnit = commodityPackingUnit;
	}

	@Column(name = "commodity_packing_quantity", nullable = false)
	public int getCommodityPackingQuantity() {
		return this.commodityPackingQuantity;
	}

	public void setCommodityPackingQuantity(int commodityPackingQuantity) {
		this.commodityPackingQuantity = commodityPackingQuantity;
	}

	@Column(name = "load_pallets_quantity", nullable = false)
	public int getLoadPalletsQuantity() {
		return this.loadPalletsQuantity;
	}

	public void setLoadPalletsQuantity(int loadPalletsQuantity) {
		this.loadPalletsQuantity = loadPalletsQuantity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "made_time", nullable = false, length = 10)
	public Date getMadeTime() {
		return this.madeTime;
	}

	public void setMadeTime(Date madeTime) {
		this.madeTime = madeTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "soon_expire", nullable = false, length = 10)
	public Date getSoonExpire() {
		return this.soonExpire;
	}

	public void setSoonExpire(Date soonExpire) {
		this.soonExpire = soonExpire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "shelf_life", nullable = false, length = 10)
	public Date getShelfLife() {
		return this.shelfLife;
	}

	public void setShelfLife(Date shelfLife) {
		this.shelfLife = shelfLife;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "load_pallets_time", nullable = false, length = 19)
	public Date getLoadPalletsTime() {
		return this.loadPalletsTime;
	}

	public void setLoadPalletsTime(Date loadPalletsTime) {
		this.loadPalletsTime = loadPalletsTime;
	}

	@Column(name = "locator_code", length = 50)
	public String getLocatorCode() {
		return this.locatorCode;
	}

	public void setLocatorCode(String locatorCode) {
		this.locatorCode = locatorCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stacking_datetime", length = 19)
	public Date getStackingDatetime() {
		return this.stackingDatetime;
	}

	public void setStackingDatetime(Date stackingDatetime) {
		this.stackingDatetime = stackingDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loadPallets")
	public Set<StockPallets> getStockPalletses() {
		return this.stockPalletses;
	}

	public void setStockPalletses(Set<StockPallets> stockPalletses) {
		this.stockPalletses = stockPalletses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loadPallets")
	public Set<StockBoxs> getStockBoxses() {
		return this.stockBoxses;
	}

	public void setStockBoxses(Set<StockBoxs> stockBoxses) {
		this.stockBoxses = stockBoxses;
	}

}
