package com.rescam.sywm.server.entity;
// Generated 2016-7-1 17:29:15 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GoodsReceiptDetail generated by hbm2java
 */
@Entity
@Table(name = "goods_receipt_detail", catalog = "sywm")
public class GoodsReceiptDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer goodsReceiptDetailId;
	private ArrivalPlan arrivalPlan;
	private ArrivalPlanDetails arrivalPlanDetails;
	private CommodityBase commodityBase;
	private CommodityPacking commodityPacking;
	private GoodsOwner goodsOwner;
	private GoodsOwnerCommodity goodsOwnerCommodity;
	private GoodsReceipt goodsReceipt;
	private String goodsOwnerCommodityCode;
	private String commodityBarcode;
	private String commodityName;
	private String commodityStandard;
	private String commodityPackingUnit;
	private int commodityPackingQuantity;
	private int arrivalPlanQuantity;
	private int receiptQuantity;
	private Date madeTime;
	private Date soonExpire;
	private Date shelfLife;
	private Integer inWarehouseQuantity;
	private Set<BoxDetail> boxDetails = new HashSet<BoxDetail>(0);

	public GoodsReceiptDetail() {
	}

	public GoodsReceiptDetail(ArrivalPlan arrivalPlan, CommodityBase commodityBase, CommodityPacking commodityPacking,
			GoodsOwner goodsOwner, GoodsOwnerCommodity goodsOwnerCommodity, GoodsReceipt goodsReceipt,
			String commodityBarcode, String commodityName, String commodityStandard, String commodityPackingUnit,
			int commodityPackingQuantity, int arrivalPlanQuantity, int receiptQuantity, Date madeTime, Date soonExpire,
			Date shelfLife) {
		this.arrivalPlan = arrivalPlan;
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.goodsReceipt = goodsReceipt;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.arrivalPlanQuantity = arrivalPlanQuantity;
		this.receiptQuantity = receiptQuantity;
		this.madeTime = madeTime;
		this.soonExpire = soonExpire;
		this.shelfLife = shelfLife;
	}

	public GoodsReceiptDetail(ArrivalPlan arrivalPlan, ArrivalPlanDetails arrivalPlanDetails,
			CommodityBase commodityBase, CommodityPacking commodityPacking, GoodsOwner goodsOwner,
			GoodsOwnerCommodity goodsOwnerCommodity, GoodsReceipt goodsReceipt, String goodsOwnerCommodityCode,
			String commodityBarcode, String commodityName, String commodityStandard, String commodityPackingUnit,
			int commodityPackingQuantity, int arrivalPlanQuantity, int receiptQuantity, Date madeTime, Date soonExpire,
			Date shelfLife, Integer inWarehouseQuantity, Set<BoxDetail> boxDetails) {
		this.arrivalPlan = arrivalPlan;
		this.arrivalPlanDetails = arrivalPlanDetails;
		this.commodityBase = commodityBase;
		this.commodityPacking = commodityPacking;
		this.goodsOwner = goodsOwner;
		this.goodsOwnerCommodity = goodsOwnerCommodity;
		this.goodsReceipt = goodsReceipt;
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
		this.commodityBarcode = commodityBarcode;
		this.commodityName = commodityName;
		this.commodityStandard = commodityStandard;
		this.commodityPackingUnit = commodityPackingUnit;
		this.commodityPackingQuantity = commodityPackingQuantity;
		this.arrivalPlanQuantity = arrivalPlanQuantity;
		this.receiptQuantity = receiptQuantity;
		this.madeTime = madeTime;
		this.soonExpire = soonExpire;
		this.shelfLife = shelfLife;
		this.inWarehouseQuantity = inWarehouseQuantity;
		this.boxDetails = boxDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "goods_receipt_detail_id", unique = true, nullable = false)
	public Integer getGoodsReceiptDetailId() {
		return this.goodsReceiptDetailId;
	}

	public void setGoodsReceiptDetailId(Integer goodsReceiptDetailId) {
		this.goodsReceiptDetailId = goodsReceiptDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "arrival_plan_id", nullable = false)
	public ArrivalPlan getArrivalPlan() {
		return this.arrivalPlan;
	}

	public void setArrivalPlan(ArrivalPlan arrivalPlan) {
		this.arrivalPlan = arrivalPlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "arrival_plan_details_id")
	public ArrivalPlanDetails getArrivalPlanDetails() {
		return this.arrivalPlanDetails;
	}

	public void setArrivalPlanDetails(ArrivalPlanDetails arrivalPlanDetails) {
		this.arrivalPlanDetails = arrivalPlanDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_base_id", nullable = false)
	public CommodityBase getCommodityBase() {
		return this.commodityBase;
	}

	public void setCommodityBase(CommodityBase commodityBase) {
		this.commodityBase = commodityBase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodity_packing_id", nullable = false)
	public CommodityPacking getCommodityPacking() {
		return this.commodityPacking;
	}

	public void setCommodityPacking(CommodityPacking commodityPacking) {
		this.commodityPacking = commodityPacking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_id", nullable = false)
	public GoodsOwner getGoodsOwner() {
		return this.goodsOwner;
	}

	public void setGoodsOwner(GoodsOwner goodsOwner) {
		this.goodsOwner = goodsOwner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_owner_commodity_id", nullable = false)
	public GoodsOwnerCommodity getGoodsOwnerCommodity() {
		return this.goodsOwnerCommodity;
	}

	public void setGoodsOwnerCommodity(GoodsOwnerCommodity goodsOwnerCommodity) {
		this.goodsOwnerCommodity = goodsOwnerCommodity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_receipt_id", nullable = false)
	public GoodsReceipt getGoodsReceipt() {
		return this.goodsReceipt;
	}

	public void setGoodsReceipt(GoodsReceipt goodsReceipt) {
		this.goodsReceipt = goodsReceipt;
	}

	@Column(name = "goods_owner_commodity_code", length = 20)
	public String getGoodsOwnerCommodityCode() {
		return this.goodsOwnerCommodityCode;
	}

	public void setGoodsOwnerCommodityCode(String goodsOwnerCommodityCode) {
		this.goodsOwnerCommodityCode = goodsOwnerCommodityCode;
	}

	@Column(name = "commodity_barcode", nullable = false, length = 20)
	public String getCommodityBarcode() {
		return this.commodityBarcode;
	}

	public void setCommodityBarcode(String commodityBarcode) {
		this.commodityBarcode = commodityBarcode;
	}

	@Column(name = "commodity_name", nullable = false, length = 50)
	public String getCommodityName() {
		return this.commodityName;
	}

	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	@Column(name = "commodity_standard", nullable = false, length = 50)
	public String getCommodityStandard() {
		return this.commodityStandard;
	}

	public void setCommodityStandard(String commodityStandard) {
		this.commodityStandard = commodityStandard;
	}

	@Column(name = "commodity_packing_unit", nullable = false, length = 10)
	public String getCommodityPackingUnit() {
		return this.commodityPackingUnit;
	}

	public void setCommodityPackingUnit(String commodityPackingUnit) {
		this.commodityPackingUnit = commodityPackingUnit;
	}

	@Column(name = "commodity_packing_quantity", nullable = false)
	public int getCommodityPackingQuantity() {
		return this.commodityPackingQuantity;
	}

	public void setCommodityPackingQuantity(int commodityPackingQuantity) {
		this.commodityPackingQuantity = commodityPackingQuantity;
	}

	@Column(name = "arrival_plan_quantity", nullable = false)
	public int getArrivalPlanQuantity() {
		return this.arrivalPlanQuantity;
	}

	public void setArrivalPlanQuantity(int arrivalPlanQuantity) {
		this.arrivalPlanQuantity = arrivalPlanQuantity;
	}

	@Column(name = "receipt_quantity", nullable = false)
	public int getReceiptQuantity() {
		return this.receiptQuantity;
	}

	public void setReceiptQuantity(int receiptQuantity) {
		this.receiptQuantity = receiptQuantity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "made_time", nullable = false, length = 10)
	public Date getMadeTime() {
		return this.madeTime;
	}

	public void setMadeTime(Date madeTime) {
		this.madeTime = madeTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "soon_expire", nullable = false, length = 10)
	public Date getSoonExpire() {
		return this.soonExpire;
	}

	public void setSoonExpire(Date soonExpire) {
		this.soonExpire = soonExpire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "shelf_life", nullable = false, length = 10)
	public Date getShelfLife() {
		return this.shelfLife;
	}

	public void setShelfLife(Date shelfLife) {
		this.shelfLife = shelfLife;
	}

	@Column(name = "in_warehouse_quantity")
	public Integer getInWarehouseQuantity() {
		return this.inWarehouseQuantity;
	}

	public void setInWarehouseQuantity(Integer inWarehouseQuantity) {
		this.inWarehouseQuantity = inWarehouseQuantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsReceiptDetail")
	public Set<BoxDetail> getBoxDetails() {
		return this.boxDetails;
	}

	public void setBoxDetails(Set<BoxDetail> boxDetails) {
		this.boxDetails = boxDetails;
	}

}
